export const OPEN_WEB_PREVIEW_URL_SCENARIO_REPLAY_DELAY_MS = 300;
export const OPEN_WEB_PREVIEW_URL_SCENARIO_REPLAY_LATE_DELAY_MS = 1200;

export const DEV_WINDOW_RESIZE_RETRY_DELAYS_MS = [0, 80, 180, 320] as const;
export const DEV_WINDOW_RESIZE_TOLERANCE_PX = 1;
export const DEV_WINDOW_UNMAXIMIZE_SETTLE_DELAY_MS = 80;

export const DEV_FEED_HINT_SCORE_STEP = 100;
export const DEV_FEED_DISPLAY_MODE_SCORE = 500;
export const DEV_FEED_MAX_UNREAD_SCORE = 100;
