[mcp_servers.tauri-mcp-server]
command = "npx"
args = [ "-y", "@hypothesi/tauri-mcp-server",]
startup_timeout_sec = 30

[mcp_servers.agentation]
command = "npx"
args = [ "-y", "agentation-mcp", "server",]
id = ""

[mcp_servers.chrome-devtools]
command = "npx"
args = [ "-y", "chrome-devtools-mcp@latest",]
id = ""

[mcp_servers.agentation.env]

[mcp_servers.chrome-devtools.env]
