// Registered in src-tauri/src/lib.rs generate_handler!; parity is enforced by tests/tauri-command-return-contract.node.test.ts.
export const TAURI_COMMAND_NAMES = [
  "add_account",
  "add_local_feed",
  "add_to_reading_list",
  "backup_database",
  "check_browser_embed_support",
  "check_for_update",
  "cleanup_feed_integrity_orphans",
  "clear_article_view_history",
  "close_browser_webview",
  "copy_to_clipboard",
  "count_account_starred_articles",
  "count_account_unread_articles",
  "count_old_unread_articles",
  "create_folder",
  "create_mute_keyword",
  "create_or_update_browser_webview",
  "create_tag",
  "create_tag_and_assign_article",
  "delete_account",
  "delete_feed",
  "delete_mute_keyword",
  "delete_tag",
  "discover_feeds",
  "download_update",
  "export_local_account_sync_operations",
  "export_opml_to_file",
  "export_settings_profile",
  "export_settings_profile_to_file",
  "focus_browser_webview",
  "get_account_cloudflare_access",
  "get_account_sync_status",
  "get_article",
  "get_article_tags",
  "get_database_info",
  "get_dev_runtime_options",
  "get_feed_integrity_report",
  "get_local_account_sync_settings",
  "get_platform_info",
  "get_platform_permission_denied_recovery",
  "get_preferences",
  "get_tag_article_counts",
  "go_back_browser_webview",
  "go_forward_browser_webview",
  "import_local_account_sync_operations",
  "import_opml",
  "import_settings_profile",
  "list_account_articles",
  "list_accounts",
  "list_articles",
  "list_articles_by_tag",
  "list_feed_article_summaries",
  "list_feeds",
  "list_folder_articles",
  "list_folders",
  "list_mute_keywords",
  "list_recent_articles",
  "list_starred_articles",
  "list_tags",
  "mark_account_read",
  "mark_account_starred_read",
  "mark_article_read",
  "mark_articles_read",
  "mark_feed_read",
  "mark_folder_read",
  "mark_old_unread_read",
  "open_in_browser",
  "open_log_dir",
  "record_article_view",
  "record_read_diagnostics_batch",
  "reload_browser_webview",
  "rename_account",
  "rename_feed",
  "rename_tag",
  "reset_oversized_dev_credentials_store",
  "restart_app",
  "search_articles",
  "set_browser_webview_bounds",
  "set_local_account_sync_settings",
  "set_mute_auto_mark_read",
  "set_preference",
  "tag_article",
  "test_account_connection",
  "toggle_article_star",
  "trigger_automatic_sync",
  "trigger_startup_sync",
  "trigger_sync",
  "trigger_sync_account",
  "trigger_sync_feed",
  "unstar_account_articles",
  "untag_article",
  "update_account_credentials",
  "update_account_sync",
  "update_feed_display_settings",
  "update_feed_folder",
  "update_mute_keyword",
  "vacuum_database",
] as const;

const TAURI_PLUGIN_COMMAND_NAMES = [
  "plugin:event|listen",
  "plugin:event|unlisten",
  "plugin:opener|open_url",
  "plugin:window|is_always_on_top",
  "plugin:window|set_always_on_top",
  "plugin:window|set_badge_count",
  "plugin:window|set_icon",
] as const;

type TauriCommandName = (typeof TAURI_COMMAND_NAMES)[number];
type TauriPluginCommandName = (typeof TAURI_PLUGIN_COMMAND_NAMES)[number];
export type InvokableCommandName = TauriCommandName | TauriPluginCommandName;

const INVOKABLE_COMMAND_NAMES: ReadonlySet<string> = new Set<string>([
  ...TAURI_COMMAND_NAMES,
  ...TAURI_PLUGIN_COMMAND_NAMES,
]);

export function isInvokableCommandName(name: string): name is InvokableCommandName {
  return INVOKABLE_COMMAND_NAMES.has(name);
}
