import { describe, expect, it } from "vitest";
import codexConfig from "../../../.codex/config.toml?raw";

// `.codex/config.toml` is generated by APM, but Codex CLI is the consumer that has to load it.
// APM 0.28.0 writes `id = ""` under each MCP server; Codex CLI 0.153.4 rejects
// `mcp_servers.<name>.id` as an unknown configuration field and exits 1 while *reading* the
// config, which kills every `codex exec` in this repository — agent workers included. The failure
// is invisible in `codex mcp list`, so only a check on the file itself catches a regenerated
// regression. See PR #274.
describe("codex config contract", () => {
  it("declares no unknown id key under mcp_servers", () => {
    const offenders = codexConfig
      .split("\n")
      .map((line, index) => ({ line: line.trim(), number: index + 1 }))
      .filter(({ line }) => /^id\s*=/.test(line))
      .map(({ number, line }) => `.codex/config.toml:${number}: ${line}`);

    expect(offenders).toEqual([]);
  });

  it("still declares the MCP servers the repository depends on", () => {
    expect(codexConfig).toContain("[mcp_servers.tauri-mcp-server]");
    expect(codexConfig).toContain("[mcp_servers.agentation]");
  });
});
