import { useSidebarAccountSectionProps } from "@/components/reader/hooks/sidebar/use-sidebar-account-section-props";
import { useSidebarContentSectionsProps } from "@/components/reader/hooks/sidebar/use-sidebar-content-sections-props";
import { useSidebarHeaderProps } from "@/components/reader/hooks/sidebar/use-sidebar-header-props";
import { useSidebarSmartViewsProps } from "@/components/reader/hooks/sidebar/use-sidebar-smart-views-props";
import type { SidebarSectionPropsParams, SidebarSectionPropsResult } from "../../sidebar.types";

export function useSidebarSectionProps({
  t,
  syncProgress,
  handleSync,
  syncTooltipLabel,
  isSyncCoolingDown,
  isSyncDisabled,
  handleAddFeed,
  selectedAccountName,
  lastSyncedLabel,
  accounts,
  accountStatusLabels,
  selectedAccountId,
  isAccountListOpen,
  accountMenuId,
  accountDropdownRef,
  accountTriggerRef,
  accountItemRefs,
  toggleAccountList,
  handleSelectAccount,
  closeAccountList,
  focusAccountList,
  visibleSmartViews,
  selectSmartView,
  isFeedsSectionOpen,
  toggleFeedsSection,
  renderSubscriptionsSectionContextMenu,
  feedViewportRef,
  openSubscriptionsIndex,
  handleOpenSettings,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  showSidebarTags,
  isTagsSectionOpen,
  toggleTagsSection,
  handleOpenAccountSettings,
  feedTreeProps,
  tags,
  tagArticleCounts,
  selection,
  selectTag,
  renderTagSectionContextMenu,
  renderTagContextMenu,
  sidebarDensity,
  isFeedTreeLoading,
  showFeedTreeSkeleton,
}: SidebarSectionPropsParams): SidebarSectionPropsResult {
  const headerProps = useSidebarHeaderProps({
    t,
    syncProgress,
    handleSync,
    syncTooltipLabel,
    isSyncCoolingDown,
    isSyncDisabled,
    handleAddFeed,
  });
  const accountSectionProps = useSidebarAccountSectionProps({
    t,
    selectedAccountName,
    lastSyncedLabel,
    accounts,
    accountStatusLabels,
    selectedAccountId,
    isAccountListOpen,
    accountMenuId,
    accountDropdownRef,
    accountTriggerRef,
    accountItemRefs,
    toggleAccountList,
    handleSelectAccount,
    closeAccountList,
    handleOpenAccountSettings,
  });
  const contentSectionsProps = useSidebarContentSectionsProps({
    t,
    isFeedsSectionOpen,
    toggleFeedsSection,
    renderSubscriptionsSectionContextMenu,
    feedViewportRef,
    openSubscriptionsIndex,
    handleOpenSettings,
    selectedAccountId,
    isAddFeedDialogOpen,
    handleAddFeedDialogOpenChange,
    showSidebarTags,
    isTagsSectionOpen,
    toggleTagsSection,
    handleOpenAccountSettings,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    selectTag,
    renderTagSectionContextMenu,
    renderTagContextMenu,
    sidebarDensity,
    isFeedTreeLoading,
    showFeedTreeSkeleton,
    onFocusAccountList: focusAccountList,
  });
  const smartViewsProps = useSidebarSmartViewsProps({
    t,
    selectedAccountId,
    visibleSmartViews,
    selectSmartView,
  });

  return {
    headerProps,
    accountSectionProps,
    smartViewsProps,
    contentSectionsProps,
  };
}
