import type { SidebarContentSectionsPropsParams } from "../../sidebar.types";
import type { SidebarContentSectionsProps } from "../../sidebar-content-sections";

export function useSidebarContentSectionsProps({
  t,
  isFeedsSectionOpen,
  toggleFeedsSection,
  renderSubscriptionsSectionContextMenu,
  feedViewportRef,
  openSubscriptionsIndex,
  handleOpenSettings,
  selectedAccountId,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  showSidebarTags,
  isTagsSectionOpen,
  toggleTagsSection,
  feedTreeProps,
  tags,
  tagArticleCounts,
  selection,
  selectTag,
  renderTagSectionContextMenu,
  renderTagContextMenu,
  sidebarDensity,
  isFeedTreeLoading,
  showFeedTreeSkeleton,
  onFocusAccountList,
}: SidebarContentSectionsPropsParams): SidebarContentSectionsProps {
  return {
    subscriptions: {
      label: t("subscriptions"),
      isOpen: isFeedsSectionOpen,
      onToggle: toggleFeedsSection,
      renderContextMenu: renderSubscriptionsSectionContextMenu,
    },
    viewportRef: feedViewportRef,
    navigation: {
      subscriptionsIndexLabel: t("subscriptions_index"),
      subscriptionsIndexShortLabel: t("subscriptions_index"),
      settingsLabel: t("settings"),
      themeToggleLabel: t("theme_toggle"),
      onOpenSubscriptionsIndex: openSubscriptionsIndex,
      onOpenSettings: handleOpenSettings,
    },
    addFeedDialog: {
      accountId: selectedAccountId,
      isOpen: isAddFeedDialogOpen,
      onOpenChange: handleAddFeedDialogOpenChange,
    },
    feedTree: {
      props: feedTreeProps,
      noFolderLabel: t("no_folder"),
      pressPlusToAddFeedLabel: t("press_plus_to_add_feed"),
      isLoading: isFeedTreeLoading,
      showSkeleton: showFeedTreeSkeleton,
    },
    tagSection: {
      isVisible: showSidebarTags,
      label: t("tags"),
      isOpen: isTagsSectionOpen,
      onToggle: toggleTagsSection,
      tags,
      tagArticleCounts,
      selection,
      onSelectTag: selectTag,
      renderSectionContextMenu: renderTagSectionContextMenu,
      renderContextMenu: renderTagContextMenu,
    },
    sidebarDensity,
    onFocusAccountList,
  };
}
