import type { SidebarContentSectionsProps, SidebarContentSectionsPropsParams } from "../../sidebar.types";

export function useSidebarContentSectionsProps({
  t,
  isFeedsSectionOpen,
  toggleFeedsSection,
  renderSubscriptionsSectionContextMenu,
  feedViewportRef,
  openSubscriptionsIndex,
  handleOpenSettings,
  selectedAccountId,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  showSidebarTags,
  isTagsSectionOpen,
  toggleTagsSection,
  feedTreeProps,
  tags,
  tagArticleCounts,
  selection,
  selectTag,
  renderTagSectionContextMenu,
  renderTagContextMenu,
  sidebarDensity,
  isFeedTreeLoading,
  showFeedTreeSkeleton,
  onFocusAccountList,
}: SidebarContentSectionsPropsParams): SidebarContentSectionsProps {
  return {
    subscriptionsLabel: t("subscriptions"),
    isFeedsSectionOpen,
    onToggleFeedsSection: toggleFeedsSection,
    renderSubscriptionsSectionContextMenu,
    viewportRef: feedViewportRef,
    subscriptionsIndexLabel: t("subscriptions_index"),
    subscriptionsIndexShortLabel: t("subscriptions_index"),
    settingsLabel: t("settings"),
    themeToggleLabel: t("theme_toggle"),
    onOpenSubscriptionsIndex: openSubscriptionsIndex,
    onOpenSettings: handleOpenSettings,
    selectedAccountId,
    isAddFeedDialogOpen,
    onAddFeedDialogOpenChange: handleAddFeedDialogOpenChange,
    pressPlusToAddFeedLabel: t("press_plus_to_add_feed"),
    tagsLabel: t("tags"),
    noFolderLabel: t("no_folder"),
    showSidebarTags,
    isTagsSectionOpen,
    onToggleTagsSection: toggleTagsSection,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    onSelectTag: selectTag,
    renderTagSectionContextMenu,
    renderTagContextMenu,
    sidebarDensity,
    isFeedTreeLoading,
    showFeedTreeSkeleton,
    onFocusAccountList,
  };
}
