import type { ComponentProps } from "react";
import type { TFunction } from "i18next";
import type { ArticleListBody } from "./article-list-body";
import type { ArticleListContextStrip } from "./article-list-context-strip";
import type { ArticleListFooter } from "./article-list-footer";
import type { ArticleListHeader } from "./article-list-header";
import type { useArticleListEffects } from "./use-article-list-effects";
import type { useArticleListGroups } from "./use-article-list-groups";
import type { useArticleListHeaderController } from "./use-article-list-header-controller";
import type { useArticleListInteractions } from "./use-article-list-interactions";
import type { useArticleListViewProps } from "./use-article-list-view-props";
import type { useArticleListViewState } from "./use-article-list-view-state";

export type ArticleListLayoutMode = "wide" | "compact" | "mobile";
export type ArticleListViewMode = "all" | "unread" | "starred";

export type ArticleListHeaderProps = ComponentProps<typeof ArticleListHeader>;
export type ArticleListContextStripProps = ComponentProps<typeof ArticleListContextStrip>;
export type ArticleListBodyProps = ComponentProps<typeof ArticleListBody>;
export type ArticleListFooterProps = ComponentProps<typeof ArticleListFooter>;

export type UseArticleListViewPropsResult = {
  layoutMode: ArticleListLayoutMode;
  headerProps: ArticleListHeaderProps;
  contextStripProps: ArticleListContextStripProps;
  bodyProps: ArticleListBodyProps;
  footerProps: ArticleListFooterProps;
};

export type UseArticleListPresentationParams = {
  t: TFunction<"reader">;
  tc: TFunction<"common">;
  ts: TFunction<"sidebar">;
  selection: Parameters<typeof useArticleListViewState>[0]["selection"];
  feedId: string | null;
  tagId: string | null;
  accountListScopeId: string | null;
  isLoading: boolean;
  isLoadingAccountArticles: boolean;
  isLoadingTagArticles: boolean;
  showSearch: boolean;
  trimmedDebouncedQuery: string;
  searchResults: Parameters<typeof useArticleListViewState>[0]["searchResults"];
  isSearching: boolean;
  filteredArticles: Parameters<typeof useArticleListEffects>[0]["filteredArticles"];
  groupedArticles: Parameters<typeof useArticleListGroups>[0]["groupedArticles"];
  groupBy: Parameters<typeof useArticleListGroups>[0]["groupBy"];
  feedNameMap: Parameters<typeof useArticleListGroups>[0]["feedNameMap"];
  selectedArticleId: string | null;
  recentlyReadIds: Parameters<typeof useArticleListGroups>[0]["recentlyReadIds"];
  selectedFeed: Parameters<typeof useArticleListHeaderController>[0]["selectedFeed"];
  layoutMode: Parameters<typeof useArticleListHeaderController>[0]["layoutMode"];
  sidebarOpen: boolean;
  openSidebar: () => void;
  toggleSidebar: () => void;
  selectArticle: (articleId: string) => void;
  clearArticle: () => void;
  openSearch: () => void;
  keyboardPrefs: Parameters<typeof useArticleListInteractions>[0]["keyboardPrefs"];
  scrollToTopOnChange: string;
  dimArchived: string;
  textPreview: string;
  imagePreviews: string;
  selectionStyle: string;
  effectiveViewMode: Parameters<typeof useArticleListViewProps>[0]["effectiveViewMode"];
  setViewMode: Parameters<typeof useArticleListViewProps>[0]["setViewMode"];
  searchQuery: string;
  searchInputRef: Parameters<typeof useArticleListViewProps>[0]["searchInputRef"];
  handleToggleSearch: () => void;
  handleCloseSearch: () => void;
  setSearchQuery: (value: string) => void;
};
