import type { CommandPaletteViewPropsResult, UseCommandPaletteViewPropsParams } from "./command-palette.types";

export function useCommandPaletteViewProps({
  title,
  description,
  placeholder,
  noResultsLabel,
  recentActionsHeading,
  actionsHeading,
  feedsHeading,
  tagsHeading,
  articlesHeading,
  recentActions,
  filteredActions,
  filteredDevScenarios,
  filteredFeeds,
  filteredTags,
  articles,
  showRecentActions,
  showActions,
  showDevScenarios,
  showFeeds,
  showTags,
  showArticles,
  hasVisibleResults,
  onActionSelect,
  onDevScenarioSelect,
  onFeedSelect,
  onTagSelect,
  onArticleSelect,
  prefixHintActions,
  prefixHintFeeds,
  prefixHintTags,
}: UseCommandPaletteViewPropsParams): CommandPaletteViewPropsResult {
  return {
    title,
    description,
    placeholder,
    resultsProps: {
      recentActions,
      filteredActions,
      filteredDevScenarios,
      filteredFeeds,
      filteredTags,
      articles,
      showRecentActions,
      showActions,
      showDevScenarios,
      showFeeds,
      showTags,
      showArticles,
      hasVisibleResults,
      noResultsLabel,
      recentActionsHeading,
      actionsHeading,
      feedsHeading,
      tagsHeading,
      articlesHeading,
      onActionSelect,
      onDevScenarioSelect,
      onFeedSelect,
      onTagSelect,
      onArticleSelect,
    },
    prefixHints: {
      actions: prefixHintActions,
      feeds: prefixHintFeeds,
      tags: prefixHintTags,
    },
  };
}
