import { useCallback } from "react";
import type { SidebarControllerSectionsParams, SidebarSectionPropsResult } from "./sidebar.types";
import { useSidebarContextMenuRenderers } from "./use-sidebar-context-menu-renderers";
import { useSidebarFeedSectionController } from "./use-sidebar-feed-section-controller";
import { useSidebarSectionProps } from "./use-sidebar-section-props";
import { useSidebarSmartViews } from "./use-sidebar-smart-views";

export function useSidebarControllerSections({
  t,
  selectedAccountId,
  feeds,
  folders,
  starredCountByFeedId,
  isFeedTreeLoading,
  showFeedTreeSkeleton,
  selection,
  viewMode,
  expandedFolderIds,
  sortSubscriptions,
  grayscaleFavicons,
  isFeedsSectionOpen,
  startupFolderExpansion,
  sidebarDensity,
  showSidebarUnread,
  showSidebarStarred,
  showSidebarRecentArticles,
  showSidebarTags,
  setExpandedFolders,
  selectFeedFromCurrentContext,
  selectFolderFromCurrentContext,
  selectAll,
  selectSmartView,
  selectTagFromCurrentContext,
  setViewMode,
  toggleFolder,
  displayFavicons,
  accounts,
  accountStatusLabels,
  selectedAccount,
  isAccountListOpen,
  accountMenuId,
  accountDropdownRef,
  accountTriggerRef,
  accountItemRefs,
  handleSelectAccount,
  closeAccountList,
  focusAccountList,
  syncProgress,
  handleSync,
  syncTooltipLabel,
  isSyncCoolingDown,
  isSyncDisabled,
  handleAddFeed,
  toggleFeedsSection,
  lastSyncedLabel,
  totalUnread,
  starredCount,
  showUnreadCount,
  showStarredCount,
  feedViewportRef,
  openSubscriptionsIndex,
  handleOpenSettings,
  handleOpenTagSettings,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  isTagsSectionOpen,
  toggleTagsSection,
  handleOpenAccountSettings,
  tags,
  tagArticleCounts,
  moveFeedToFolder,
  moveFeedToUnfoldered,
}: SidebarControllerSectionsParams): SidebarSectionPropsResult {
  const visibleSmartViews = useSidebarSmartViews({
    selection,
    totalUnread,
    starredCount,
    showUnreadCount,
    showStarredCount,
    showSidebarUnread,
    showSidebarStarred,
    showSidebarRecentArticles,
    t,
  });
  const {
    renderFolderContextMenu,
    renderFeedContextMenu,
    renderTagContextMenu,
    renderTagSectionContextMenu,
    renderSubscriptionsSectionContextMenu,
  } = useSidebarContextMenuRenderers({
    folders,
    setExpandedFolders,
    onManageTags: handleOpenTagSettings,
  });
  const handleSelectTag = useCallback(
    (tagId: string) => {
      selectTagFromCurrentContext(tagId);
    },
    [selectTagFromCurrentContext],
  );
  const { feedTreeProps } = useSidebarFeedSectionController({
    selectedAccountId,
    feeds,
    folders,
    starredCountByFeedId,
    selection,
    viewMode,
    expandedFolderIds,
    sortSubscriptions,
    grayscaleFavicons,
    isFeedsSectionOpen,
    startupFolderExpansion,
    sidebarDensity,
    showSidebarUnread,
    showSidebarStarred,
    showSidebarRecentArticles,
    showSidebarTags,
    tags,
    setExpandedFolders,
    selectFeed: selectFeedFromCurrentContext,
    selectFolder: selectFolderFromCurrentContext,
    selectAll,
    selectSmartView,
    setViewMode,
    toggleFolder,
    displayFavicons,
    moveFeedToFolder,
    moveFeedToUnfoldered,
    renderFolderContextMenu,
    renderFeedContextMenu,
  });

  return useSidebarSectionProps({
    t,
    syncProgress,
    handleSync,
    syncTooltipLabel,
    isSyncCoolingDown,
    isSyncDisabled,
    handleAddFeed,
    selectedAccountName: selectedAccount?.name,
    lastSyncedLabel,
    accounts: accounts ?? [],
    accountStatusLabels,
    selectedAccountId,
    isAccountListOpen,
    accountMenuId,
    accountDropdownRef,
    accountTriggerRef,
    accountItemRefs,
    toggleAccountList: focusAccountList,
    handleSelectAccount,
    closeAccountList,
    focusAccountList,
    visibleSmartViews,
    selectSmartView,
    isFeedsSectionOpen,
    toggleFeedsSection,
    feedViewportRef,
    openSubscriptionsIndex,
    handleOpenSettings,
    isAddFeedDialogOpen,
    handleAddFeedDialogOpenChange,
    showSidebarTags,
    isTagsSectionOpen,
    toggleTagsSection,
    handleOpenAccountSettings,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    selectTag: handleSelectTag,
    renderTagSectionContextMenu,
    renderTagContextMenu,
    renderSubscriptionsSectionContextMenu,
    sidebarDensity,
    isFeedTreeLoading,
    showFeedTreeSkeleton,
  });
}
