import { useTranslation } from "react-i18next";
import type { UseArticleListViewPropsResult } from "./article-list.types";
import { useArticleListData } from "./use-article-list-data";
import { useArticleListPresentation } from "./use-article-list-presentation";
import { useArticleListRuntime } from "./use-article-list-runtime";

export function useArticleListController(): UseArticleListViewPropsResult {
  const { t } = useTranslation("reader");
  const { t: tc } = useTranslation("common");
  const { t: ts } = useTranslation("sidebar");
  const {
    selection,
    selectedArticleId,
    selectArticle,
    clearArticle,
    openSidebar,
    toggleSidebar,
    sidebarOpen,
    viewMode,
    setViewMode,
    layoutMode,
    recentlyReadIds,
    retainedArticleIds,
    keyboardPrefs,
    sortUnread,
    groupBy,
    dimArchived,
    textPreview,
    imagePreviews,
    selectionStyle,
    scrollToTopOnChange,
    feedId,
    folderId,
    tagId,
    smartViewKind,
    accountListScopeId,
    feeds,
    articles,
    accountArticles,
    tagArticles,
    isLoading,
    isLoadingAccountArticles,
    isLoadingTagArticles,
    showSearch,
    searchQuery,
    searchInputRef,
    trimmedDebouncedQuery,
    searchResults,
    isSearching,
    openSearch,
    handleToggleSearch,
    handleCloseSearch,
    setSearchQuery,
  } = useArticleListRuntime();

  const {
    feedId: resolvedFeedId,
    tagId: resolvedTagId,
    accountListScopeId: resolvedAccountListScopeId,
    effectiveViewMode,
    feedNameMap,
    filteredArticles,
    groupedArticles,
    selectedFeed,
  } = useArticleListData({
    selection,
    feedId,
    folderId,
    tagId,
    smartViewKind,
    accountListScopeId,
    viewMode,
    selectedArticleId,
    retainedArticleIds,
    feeds,
    articles,
    accountArticles,
    tagArticles,
    searchResults,
    showSearch,
    trimmedDebouncedQuery,
    sortUnread,
    groupBy,
  });

  return useArticleListPresentation({
    t,
    tc,
    ts,
    selection,
    feedId: resolvedFeedId,
    tagId: resolvedTagId,
    accountListScopeId: resolvedAccountListScopeId,
    isLoading,
    isLoadingAccountArticles,
    isLoadingTagArticles,
    showSearch,
    trimmedDebouncedQuery,
    searchResults,
    isSearching,
    filteredArticles,
    groupedArticles,
    groupBy,
    feedNameMap,
    selectedArticleId,
    recentlyReadIds,
    selectedFeed,
    layoutMode,
    sidebarOpen,
    openSidebar,
    toggleSidebar,
    selectArticle,
    clearArticle,
    openSearch,
    keyboardPrefs,
    scrollToTopOnChange,
    dimArchived,
    textPreview,
    imagePreviews,
    selectionStyle,
    effectiveViewMode,
    setViewMode,
    searchQuery,
    searchInputRef,
    handleToggleSearch,
    handleCloseSearch,
    setSearchQuery,
  });
}
