import type { SidebarContentSectionsProps, SidebarContentSectionsPropsParams } from "./sidebar.types";

export function useSidebarContentSectionsProps({
  t,
  isFeedsSectionOpen,
  toggleFeedsSection,
  feedViewportRef,
  openFeedCleanup,
  handleOpenSettings,
  selectedAccountId,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  showSidebarTags,
  isTagsSectionOpen,
  toggleTagsSection,
  handleOpenAccountSettings,
  feedTreeProps,
  tags,
  tagArticleCounts,
  selection,
  selectTag,
  renderTagContextMenu,
  sidebarDensity,
  isFeedTreeLoading,
}: SidebarContentSectionsPropsParams): SidebarContentSectionsProps {
  return {
    subscriptionsLabel: t("subscriptions"),
    isFeedsSectionOpen,
    onToggleFeedsSection: toggleFeedsSection,
    viewportRef: feedViewportRef,
    feedCleanupLabel: t("feed_cleanup"),
    settingsLabel: t("settings"),
    onOpenFeedCleanup: openFeedCleanup,
    onOpenSettings: handleOpenSettings,
    selectedAccountId,
    isAddFeedDialogOpen,
    onAddFeedDialogOpenChange: handleAddFeedDialogOpenChange,
    addAccountToStartLabel: t("add_account_to_start"),
    pressPlusToAddFeedLabel: t("press_plus_to_add_feed"),
    tagsLabel: t("tags"),
    noFolderLabel: t("no_folder"),
    showSidebarTags,
    isTagsSectionOpen,
    onToggleTagsSection: toggleTagsSection,
    onOpenAccountSettings: handleOpenAccountSettings,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    onSelectTag: selectTag,
    renderTagContextMenu,
    sidebarDensity,
    isFeedTreeLoading,
  };
}
