import { useTranslation } from "react-i18next";
import { useUpdateFeedFolder } from "@/hooks/use-update-feed-folder";
import type { SidebarControllerResult } from "./sidebar.types";
import { useSidebarAccountSelection } from "./use-sidebar-account-selection";
import { useSidebarContextMenuRenderers } from "./use-sidebar-context-menu-renderers";
import { useSidebarControllerActions } from "./use-sidebar-controller-actions";
import { useSidebarFeedSectionController } from "./use-sidebar-feed-section-controller";
import { useSidebarRuntime } from "./use-sidebar-runtime";
import { useSidebarSectionProps } from "./use-sidebar-section-props";
import { useSidebarSmartViews } from "./use-sidebar-smart-views";
import { useSidebarViewProps } from "./use-sidebar-view-props";

export function useSidebarController(): SidebarControllerResult {
  const { t } = useTranslation("sidebar");
  const {
    isFeedsSectionOpen,
    setIsFeedsSectionOpen,
    isTagsSectionOpen,
    setIsTagsSectionOpen,
    isAccountListOpen,
    accountDropdownRef,
    accountTriggerRef,
    accountItemRefs,
    accountMenuId,
    closeAccountList,
    toggleAccountList,
    layoutMode,
    selectedAccountId,
    selectAccount,
    restoreAccountSelection,
    clearSelectedAccount,
    selection,
    viewMode,
    selectFeed,
    selectFolder,
    selectAll,
    selectSmartView,
    selectTag,
    setViewMode,
    expandedFolderIds,
    setExpandedFolders,
    toggleFolder,
    openSettings,
    openFeedCleanup,
    isAddFeedDialogOpen,
    openAddFeedDialog,
    closeAddFeedDialog,
    setSettingsAddAccount,
    syncProgress,
    showUnreadCount,
    showStarredCount,
    showSidebarUnread,
    showSidebarStarred,
    showSidebarTags,
    displayFavicons,
    grayscaleFavicons,
    sortSubscriptions,
    startupFolderExpansion,
    opaqueSidebars,
    savedAccountId,
    setPref,
    accounts,
    accountStatusLabels,
    selectedAccount,
    feeds,
    folders,
    tags,
    tagArticleCounts,
    totalUnread,
    starredCount,
    feedViewportRef,
    activeDevIntent,
    handleSync,
    lastSyncedLabel,
  } = useSidebarRuntime();
  const updateFeedFolderMutation = useUpdateFeedFolder();

  const {
    setSelectedAccountPreference,
    moveFeedToFolder,
    moveFeedToUnfoldered,
    handleSelectAccount,
    toggleFeedsSection,
    toggleTagsSection,
    handleOpenSettings,
    handleOpenAccountSettings,
    handleAddFeed,
    handleAddFeedDialogOpenChange,
  } = useSidebarControllerActions({
    selectedAccountId,
    selectAccount,
    openSettings,
    setSettingsAddAccount,
    openAddFeedDialog,
    closeAddFeedDialog,
    setIsFeedsSectionOpen,
    setIsTagsSectionOpen,
    setPref,
    updateFeedFolder: updateFeedFolderMutation.mutateAsync,
  });

  useSidebarAccountSelection({
    accounts,
    selectedAccountId,
    savedAccountId,
    layoutMode,
    activeDevIntent,
    clearSelectedAccount,
    restoreAccountSelection,
    setSelectedAccountPreference,
  });

  const visibleSmartViews = useSidebarSmartViews({
    selection,
    totalUnread,
    starredCount,
    showUnreadCount,
    showStarredCount,
    showSidebarUnread,
    showSidebarStarred,
    t,
  });
  const { renderFolderContextMenu, renderFeedContextMenu, renderTagContextMenu } = useSidebarContextMenuRenderers();
  const { feedTreeProps } = useSidebarFeedSectionController({
    selectedAccountId,
    feeds,
    folders,
    selection,
    viewMode,
    expandedFolderIds,
    sortSubscriptions,
    grayscaleFavicons,
    isFeedsSectionOpen,
    startupFolderExpansion,
    showSidebarUnread,
    showSidebarStarred,
    showSidebarTags,
    setExpandedFolders,
    selectFeed,
    selectFolder,
    selectAll,
    selectSmartView,
    setViewMode,
    toggleFolder,
    displayFavicons,
    moveFeedToFolder,
    moveFeedToUnfoldered,
    renderFolderContextMenu,
    renderFeedContextMenu,
  });

  const { headerProps, accountSectionProps, smartViewsProps, contentSectionsProps } = useSidebarSectionProps({
    t,
    syncProgress,
    handleSync,
    handleAddFeed,
    selectedAccountName: selectedAccount?.name,
    lastSyncedLabel,
    accounts: accounts ?? [],
    accountStatusLabels,
    selectedAccountId,
    isAccountListOpen,
    accountMenuId,
    accountDropdownRef,
    accountTriggerRef,
    accountItemRefs,
    toggleAccountList,
    handleSelectAccount,
    closeAccountList,
    visibleSmartViews,
    selectSmartView,
    isFeedsSectionOpen,
    toggleFeedsSection,
    feedViewportRef,
    openFeedCleanup,
    handleOpenSettings,
    isAddFeedDialogOpen,
    handleAddFeedDialogOpenChange,
    showSidebarTags,
    isTagsSectionOpen,
    toggleTagsSection,
    handleOpenAccountSettings,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    selectTag,
    renderTagContextMenu,
  });

  return useSidebarViewProps({
    opaqueSidebars,
    headerProps,
    accountSectionProps,
    smartViewsProps,
    contentSectionsProps,
  });
}
