import type { SidebarControllerSectionsParams, SidebarSectionPropsResult } from "./sidebar.types";
import { useSidebarContextMenuRenderers } from "./use-sidebar-context-menu-renderers";
import { useSidebarFeedSectionController } from "./use-sidebar-feed-section-controller";
import { useSidebarSectionProps } from "./use-sidebar-section-props";
import { useSidebarSmartViews } from "./use-sidebar-smart-views";

export function useSidebarControllerSections({
  t,
  selectedAccountId,
  feeds,
  folders,
  isFeedTreeLoading,
  selection,
  viewMode,
  expandedFolderIds,
  sortSubscriptions,
  grayscaleFavicons,
  isFeedsSectionOpen,
  startupFolderExpansion,
  sidebarDensity,
  showSidebarUnread,
  showSidebarStarred,
  showSidebarTags,
  setExpandedFolders,
  selectFeed,
  selectFolder,
  selectAll,
  selectSmartView,
  selectTag,
  setViewMode,
  toggleFolder,
  displayFavicons,
  accounts,
  accountStatusLabels,
  selectedAccount,
  isAccountListOpen,
  accountMenuId,
  accountDropdownRef,
  accountTriggerRef,
  accountItemRefs,
  toggleAccountList,
  handleSelectAccount,
  closeAccountList,
  syncProgress,
  handleSync,
  handleAddFeed,
  toggleFeedsSection,
  lastSyncedLabel,
  totalUnread,
  starredCount,
  showUnreadCount,
  showStarredCount,
  feedViewportRef,
  openFeedCleanup,
  handleOpenSettings,
  handleOpenTagSettings,
  isAddFeedDialogOpen,
  handleAddFeedDialogOpenChange,
  isTagsSectionOpen,
  toggleTagsSection,
  handleOpenAccountSettings,
  tags,
  tagArticleCounts,
  moveFeedToFolder,
  moveFeedToUnfoldered,
  handleAddTag,
}: SidebarControllerSectionsParams): SidebarSectionPropsResult {
  const visibleSmartViews = useSidebarSmartViews({
    selection,
    totalUnread,
    starredCount,
    showUnreadCount,
    showStarredCount,
    showSidebarUnread,
    showSidebarStarred,
    t,
  });
  const { renderFolderContextMenu, renderFeedContextMenu, renderTagContextMenu, renderTagSectionContextMenu } =
    useSidebarContextMenuRenderers({
      onAddTag: handleAddTag,
      onManageTags: handleOpenTagSettings,
    });
  const { feedTreeProps } = useSidebarFeedSectionController({
    selectedAccountId,
    feeds,
    folders,
    selection,
    viewMode,
    expandedFolderIds,
    sortSubscriptions,
    grayscaleFavicons,
    isFeedsSectionOpen,
    startupFolderExpansion,
    sidebarDensity,
    showSidebarUnread,
    showSidebarStarred,
    showSidebarTags,
    setExpandedFolders,
    selectFeed,
    selectFolder,
    selectAll,
    selectSmartView,
    setViewMode,
    toggleFolder,
    displayFavicons,
    moveFeedToFolder,
    moveFeedToUnfoldered,
    renderFolderContextMenu,
    renderFeedContextMenu,
  });

  return useSidebarSectionProps({
    t,
    syncProgress,
    handleSync,
    handleAddFeed,
    selectedAccountName: selectedAccount?.name,
    lastSyncedLabel,
    accounts: accounts ?? [],
    accountStatusLabels,
    selectedAccountId,
    isAccountListOpen,
    accountMenuId,
    accountDropdownRef,
    accountTriggerRef,
    accountItemRefs,
    toggleAccountList,
    handleSelectAccount,
    closeAccountList,
    visibleSmartViews,
    selectSmartView,
    isFeedsSectionOpen,
    toggleFeedsSection,
    feedViewportRef,
    openFeedCleanup,
    handleOpenSettings,
    isAddFeedDialogOpen,
    handleAddFeedDialogOpenChange,
    showSidebarTags,
    isTagsSectionOpen,
    toggleTagsSection,
    handleOpenAccountSettings,
    feedTreeProps,
    tags,
    tagArticleCounts,
    selection,
    selectTag,
    renderTagSectionContextMenu,
    renderTagContextMenu,
    sidebarDensity,
    isFeedTreeLoading,
  });
}
