import { useArticleListBodyProps } from "@/components/reader/hooks/article-list/use-article-list-body-props";
import type { UseArticleListViewPropsParams, UseArticleListViewPropsResult } from "./article-list-controller.types";

export function useArticleListViewProps({
  t,
  tc,
  layoutMode,
  showSearch,
  searchQuery,
  searchInputRef,
  showSidebarButton,
  sidebarButtonLabel,
  sidebarButtonText,
  isSidebarVisible,
  feedModeControl,
  handleMarkAllRead,
  handleSidebarToggle,
  handleToggleSearch,
  handleCloseSearch,
  setSearchQuery,
  contextStripContext,
  listRef,
  viewportRef,
  handleListKeyDownCapture,
  isLoadingFeedArticles,
  isLoadingAccountArticles,
  isLoadingFolderArticles,
  isLoadingRecentArticles,
  isLoadingTagArticles,
  isSearchLoading,
  isSearchEmptyState,
  setupEmptyState,
  trimmedDebouncedQuery,
  articleGroups,
  dimArchived,
  textPreview,
  imagePreviews,
  selectionStyle,
  selectArticle,
  onManageSelectedFeed,
  effectiveViewMode,
  footerModes,
  footerDisabledModes,
  setViewMode,
}: UseArticleListViewPropsParams): UseArticleListViewPropsResult {
  const bodyProps = useArticleListBodyProps({
    t,
    tc,
    listRef,
    viewportRef,
    handleListKeyDownCapture,
    isLoadingFeedArticles,
    isLoadingAccountArticles,
    isLoadingFolderArticles,
    isLoadingRecentArticles,
    isLoadingTagArticles,
    isSearchLoading,
    isSearchEmptyState,
    setupEmptyState,
    trimmedDebouncedQuery,
    articleGroups,
    dimArchived,
    textPreview,
    imagePreviews,
    selectionStyle,
    selectArticle,
    onManageSelectedFeed,
    handleCloseSearch,
    handleMarkAllRead,
  });

  return {
    layoutMode,
    headerProps: {
      showSearch,
      searchQuery,
      searchInputRef,
      labels: {
        markAllReadLabel: t("mark_all_as_read"),
        markAllReadButtonText: t("mark_all_read_short"),
        searchArticlesLabel: t("search_articles"),
        searchArticlesButtonText: t("search_short"),
        closeSearchLabel: t("close_search"),
        searchArticlesPlaceholder: t("search_articles_placeholder"),
        searchArticlesDescription: t("search_articles_description"),
      },
      showSidebarButton,
      sidebarButtonLabel,
      sidebarButtonText,
      isSidebarVisible,
      feedModeControl,
      onMarkAllRead: handleMarkAllRead,
      onToggleSidebar: handleSidebarToggle,
      onToggleSearch: handleToggleSearch,
      onCloseSearch: handleCloseSearch,
      onSearchQueryChange: setSearchQuery,
    },
    contextStripProps: {
      primaryLabel: contextStripContext.primaryLabel,
      secondaryLabel: contextStripContext.secondaryLabel,
      tone: contextStripContext.tone,
    },
    bodyProps,
    footerProps: {
      viewMode: effectiveViewMode,
      modes: footerModes,
      disabledModes: footerDisabledModes,
      onSetViewMode: setViewMode,
    },
  };
}
