import { useArticleListEffects } from "@/components/reader/hooks/article-list/use-article-list-effects";
import { useArticleListGroups } from "@/components/reader/hooks/article-list/use-article-list-groups";
import { useArticleListHeaderController } from "@/components/reader/hooks/article-list/use-article-list-header-controller";
import { useArticleListInteractions } from "@/components/reader/hooks/article-list/use-article-list-interactions";
import { useArticleListViewProps } from "@/components/reader/hooks/article-list/use-article-list-view-props";
import { useArticleListViewState } from "@/components/reader/hooks/article-list/use-article-list-view-state";
import type { UseArticleListPresentationParams, UseArticleListViewPropsResult } from "./article-list-controller.types";

export function useArticleListPresentation({
  t,
  tc,
  ts,
  selection,
  focusedPane,
  selectedAccountId,
  accountCount,
  feeds,
  feedId,
  tagId,
  accountListScopeId,
  isLoadingFeedArticles,
  isLoadingAccountArticles,
  isLoadingFolderArticles,
  isLoadingRecentArticles,
  isLoadingTagArticles,
  showSearch,
  trimmedDebouncedQuery,
  searchResults,
  isSearching,
  filteredArticles,
  groupedArticles,
  groupBy,
  feedNameMap,
  selectedArticleId,
  recentlyReadIds,
  selectedFeed,
  onManageSelectedFeed,
  layoutMode,
  contentMode,
  sidebarOpen,
  openSidebar,
  toggleSidebar,
  setWebPreviewSessionMode,
  selectArticle,
  clearArticle,
  openSearch,
  keyboardPrefs,
  scrollToTopOnChange,
  dimArchived,
  textPreview,
  imagePreviews,
  selectionStyle,
  effectiveViewMode,
  setViewMode,
  searchQuery,
  searchInputRef,
  handleToggleSearch,
  handleCloseSearch,
  setSearchQuery,
}: UseArticleListPresentationParams): UseArticleListViewPropsResult {
  const viewState = useArticleListViewState({
    selection,
    t,
    selectedAccountId,
    feedId,
    tagId,
    accountListScopeId,
    accountCount,
    feedCount: feeds?.length,
    isLoadingFeedArticles,
    isLoadingAccountArticles,
    isLoadingFolderArticles,
    isLoadingRecentArticles,
    isLoadingTagArticles,
    showSearch,
    trimmedDebouncedQuery,
    searchResults,
    isSearching,
    filteredArticleCount: filteredArticles.length,
  });

  const articleGroups = useArticleListGroups({
    groupedArticles,
    groupBy,
    feedNameMap,
    selectedArticleId,
    recentlyReadIds,
    t,
  });

  const headerController = useArticleListHeaderController({
    selection,
    feeds,
    feedId,
    selectedFeed,
    filteredArticles,
    layoutMode,
    sidebarOpen,
    showSearch,
    contentMode,
    sidebarSubscriptionsLabel: ts("subscriptions"),
    showSidebarLabel: t("show_sidebar"),
    hideSidebarLabel: t("hide_sidebar"),
    openSidebar,
    toggleSidebar,
    setWebPreviewSessionMode,
  });
  const { handleMarkAllRead, ...headerControls } = headerController;

  const { listRef, viewportRef, handleListKeyDownCapture } = useArticleListInteractions({
    filteredArticles,
    selectedArticleId,
    selectArticle,
    clearArticle,
    openSidebar,
    toggleSidebar,
    openSearch,
    handleMarkAllRead,
    keyboardPrefs,
  });

  useArticleListEffects({
    selection,
    scrollToTopOnChange,
    listRef,
    viewportRef,
    filteredArticles,
    focusedPane,
    selectedArticleId,
    isPrimarySourceLoading: viewState.isPrimarySourceLoading,
    isSearchLoading: viewState.isSearchLoading,
    clearArticle,
  });

  return useArticleListViewProps({
    t,
    tc,
    layoutMode,
    contentMode,
    showSearch,
    searchQuery,
    searchInputRef,
    handleMarkAllRead,
    handleToggleSearch,
    handleCloseSearch,
    setSearchQuery,
    listRef,
    viewportRef,
    handleListKeyDownCapture,
    isLoadingFeedArticles,
    isLoadingAccountArticles,
    isLoadingFolderArticles,
    isLoadingRecentArticles,
    isLoadingTagArticles,
    trimmedDebouncedQuery,
    articleGroups,
    dimArchived,
    textPreview,
    imagePreviews,
    selectionStyle,
    selectArticle,
    onManageSelectedFeed,
    effectiveViewMode,
    setViewMode,
    ...headerControls,
    ...viewState,
  });
}
