export const MOTION_INTERACTIVE_SURFACE_CLASS_NAME = "motion-interactive-surface";
export const MOTION_BUTTON_SURFACE_CLASS_NAME = "motion-button-surface";
export const MOTION_DISCLOSURE_PANEL_CLASS_NAME = "motion-disclosure-panel";
export const MOTION_DISCLOSURE_TRIGGER_CLASS_NAME = "motion-disclosure-trigger";
export const MOTION_CONTENT_SWAP_CLASS_NAME = "motion-content-swap";
export const MOTION_ARTICLE_SLIDE_CLASS_NAME = "motion-article-slide";
export const MOTION_CONTEXTUAL_SURFACE_CLASS_NAME = "motion-contextual-surface";
export const MOTION_STATIC_HOVER_SURFACE_CLASS_NAME = "motion-static-hover-surface";
export const MOTION_RESIZE_SURFACE_CLASS_NAME = "motion-resize-surface";
export const MOTION_POPUP_SURFACE_CLASS_NAME = "motion-popup-surface";
export const MOTION_POPUP_OVERLAY_CLASS_NAME = "motion-popup-overlay";
export const MOTION_POPUP_DIALOG_CLASS_NAME = "motion-popup-dialog";
export const MOTION_BROWSER_OVERLAY_CLASS_NAME = "motion-browser-overlay-panel";
export const MOTION_BROWSER_THEME_WIPE_OVERLAY_CLASS_NAME = "motion-browser-theme-wipe-overlay";
export const MOTION_DIGIT_GROUP_CLASS_NAME = "t-digit-group";
export const MOTION_DIGIT_CLASS_NAME = "t-digit";
export const MOTION_DIGIT_ANIMATING_CLASS_NAME = "is-animating";
export const MOTION_ICON_SWAP_CLASS_NAME = "motion-icon-swap";
export const MOTION_ICON_SWAP_ICON_CLASS_NAME = "motion-icon-swap-icon";
export const MOTION_CLASS_NAMES = [
  MOTION_INTERACTIVE_SURFACE_CLASS_NAME,
  MOTION_BUTTON_SURFACE_CLASS_NAME,
  MOTION_DISCLOSURE_PANEL_CLASS_NAME,
  MOTION_DISCLOSURE_TRIGGER_CLASS_NAME,
  MOTION_CONTENT_SWAP_CLASS_NAME,
  MOTION_ARTICLE_SLIDE_CLASS_NAME,
  MOTION_CONTEXTUAL_SURFACE_CLASS_NAME,
  MOTION_STATIC_HOVER_SURFACE_CLASS_NAME,
  MOTION_RESIZE_SURFACE_CLASS_NAME,
  MOTION_POPUP_SURFACE_CLASS_NAME,
  MOTION_POPUP_OVERLAY_CLASS_NAME,
  MOTION_POPUP_DIALOG_CLASS_NAME,
  MOTION_BROWSER_OVERLAY_CLASS_NAME,
  MOTION_BROWSER_THEME_WIPE_OVERLAY_CLASS_NAME,
  MOTION_DIGIT_GROUP_CLASS_NAME,
  MOTION_DIGIT_CLASS_NAME,
  MOTION_DIGIT_ANIMATING_CLASS_NAME,
  MOTION_ICON_SWAP_CLASS_NAME,
  MOTION_ICON_SWAP_ICON_CLASS_NAME,
] as const;
export type MotionClassName = (typeof MOTION_CLASS_NAMES)[number];

export const MOTION_VERTICAL_WIPE_KEYFRAMES_NAME = "vertical-wipe";
export const MOTION_CONTENT_SWAP_ENTER_KEYFRAMES_NAME = "motion-content-swap-enter";
export const MOTION_ARTICLE_SLIDE_NEXT_KEYFRAMES_NAME = "motion-article-slide-next";
export const MOTION_ARTICLE_SLIDE_PREV_KEYFRAMES_NAME = "motion-article-slide-prev";
export const MOTION_DIGIT_POP_IN_KEYFRAMES_NAME = "t-digit-pop-in";
export const MOTION_KEYFRAMES_NAMES = [
  MOTION_VERTICAL_WIPE_KEYFRAMES_NAME,
  MOTION_CONTENT_SWAP_ENTER_KEYFRAMES_NAME,
  MOTION_ARTICLE_SLIDE_NEXT_KEYFRAMES_NAME,
  MOTION_ARTICLE_SLIDE_PREV_KEYFRAMES_NAME,
  MOTION_DIGIT_POP_IN_KEYFRAMES_NAME,
] as const;
export type MotionKeyframesName = (typeof MOTION_KEYFRAMES_NAMES)[number];

export const MOTION_DATA_PHASE_ATTRIBUTE = "data-motion-phase";
export const MOTION_DATA_DIRECTION_ATTRIBUTE = "data-motion-direction";
export const MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE = "data-article-slide-content";
export const MOTION_DATA_STATE_ATTRIBUTE = "data-state";
export const MOTION_DATA_ICON_ATTRIBUTE = "data-icon";
export const MOTION_DATA_SIDE_ATTRIBUTE = "data-side";
export const MOTION_DATA_STAGGER_ATTRIBUTE = "data-stagger";
export const MOTION_DATA_OPEN_ATTRIBUTE = "data-open";
export const MOTION_DATA_CLOSED_ATTRIBUTE = "data-closed";
export const MOTION_DATA_STARTING_STYLE_ATTRIBUTE = "data-starting-style";
export const MOTION_DATA_ENDING_STYLE_ATTRIBUTE = "data-ending-style";
export const MOTION_DATA_ATTRIBUTES = [
  MOTION_DATA_PHASE_ATTRIBUTE,
  MOTION_DATA_DIRECTION_ATTRIBUTE,
  MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE,
  MOTION_DATA_STATE_ATTRIBUTE,
  MOTION_DATA_ICON_ATTRIBUTE,
  MOTION_DATA_SIDE_ATTRIBUTE,
  MOTION_DATA_STAGGER_ATTRIBUTE,
  MOTION_DATA_OPEN_ATTRIBUTE,
  MOTION_DATA_CLOSED_ATTRIBUTE,
  MOTION_DATA_STARTING_STYLE_ATTRIBUTE,
  MOTION_DATA_ENDING_STYLE_ATTRIBUTE,
] as const;
export type MotionDataAttribute = (typeof MOTION_DATA_ATTRIBUTES)[number];

export const MOTION_POPUP_SIDE_TOP = "top";
export type MotionPopupSide = typeof MOTION_POPUP_SIDE_TOP;

export const MOTION_PHASE_STEADY = "steady";
export const MOTION_PHASE_ENTERING = "entering";
export type MotionPhase = typeof MOTION_PHASE_STEADY | typeof MOTION_PHASE_ENTERING;

export const MOTION_DIRECTION_NEXT = "next";
export const MOTION_DIRECTION_PREV = "prev";
export const MOTION_DIRECTION_NEUTRAL = "neutral";
export type MotionDirection =
  | typeof MOTION_DIRECTION_NEXT
  | typeof MOTION_DIRECTION_PREV
  | typeof MOTION_DIRECTION_NEUTRAL;

export const MOTION_STATE_OPEN = "open";
export const MOTION_STATE_CLOSED = "closed";
export type MotionDisclosureState = typeof MOTION_STATE_OPEN | typeof MOTION_STATE_CLOSED;

export const BROWSER_OVERLAY_CLOSE_DELAY_MS = 350;

export const MOTION_ICON_SWAP_STATE_A = "a";
export const MOTION_ICON_SWAP_STATE_B = "b";
export type MotionIconSwapState = typeof MOTION_ICON_SWAP_STATE_A | typeof MOTION_ICON_SWAP_STATE_B;

export const MOTION_ICON_SWAP_ICON_A = "a";
export const MOTION_ICON_SWAP_ICON_B = "b";
export type MotionIconSwapIcon = typeof MOTION_ICON_SWAP_ICON_A | typeof MOTION_ICON_SWAP_ICON_B;

export const MOTION_DIGIT_STAGGER_ONE = "1";
export const MOTION_DIGIT_STAGGER_TWO = "2";
export type MotionDigitStagger = typeof MOTION_DIGIT_STAGGER_ONE | typeof MOTION_DIGIT_STAGGER_TWO;

export const MOTION_GLOBAL_CSS_CONTRACT_SELECTORS = [
  `.${MOTION_CONTENT_SWAP_CLASS_NAME}[${MOTION_DATA_PHASE_ATTRIBUTE}="${MOTION_PHASE_ENTERING}"]`,
  `.${MOTION_ARTICLE_SLIDE_CLASS_NAME}[${MOTION_DATA_DIRECTION_ATTRIBUTE}="${MOTION_DIRECTION_NEXT}"]`,
  `.${MOTION_ARTICLE_SLIDE_CLASS_NAME}[${MOTION_DATA_DIRECTION_ATTRIBUTE}="${MOTION_DIRECTION_PREV}"]`,
  `[${MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE}="true"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_A}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_A}"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_B}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_B}"]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_SIDE_ATTRIBUTE}="${MOTION_POPUP_SIDE_TOP}"]`,
  `.${MOTION_POPUP_OVERLAY_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}]`,
  `.${MOTION_POPUP_OVERLAY_CLASS_NAME}[${MOTION_DATA_CLOSED_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_STARTING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_ENDING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_BROWSER_OVERLAY_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}="true"]`,
] as const;
export type MotionGlobalCssContractSelector = (typeof MOTION_GLOBAL_CSS_CONTRACT_SELECTORS)[number];
