export const MOTION_INTERACTIVE_SURFACE_CLASS_NAME = "motion-interactive-surface";
export const MOTION_BUTTON_SURFACE_CLASS_NAME = "motion-button-surface";
const MOTION_DISCLOSURE_PANEL_CLASS_NAME = "motion-disclosure-panel";
const MOTION_DISCLOSURE_BODY_CLASS_NAME = "motion-disclosure-body";
export const MOTION_DISCLOSURE_TRIGGER_CLASS_NAME = "motion-disclosure-trigger";
const MOTION_DISCLOSURE_ICON_CLASS_NAME = "motion-disclosure-icon";
export const MOTION_CONTENT_SWAP_CLASS_NAME = "motion-content-swap";
// Shared --motion-duration-content-swap (180ms/4px) is tuned for small toggle pops;
// large content-swap surfaces (article list, selection summary) use this slower/larger pair instead.
export const MOTION_CONTENT_SWAP_SLOW_DURATION_MS = "260ms";
export const MOTION_CONTENT_SWAP_SLOW_OFFSET_PX = "10px";
export const MOTION_ARTICLE_SLIDE_CLASS_NAME = "motion-article-slide";
export const MOTION_CONTEXTUAL_SURFACE_CLASS_NAME = "motion-contextual-surface";
const MOTION_STATIC_HOVER_SURFACE_CLASS_NAME = "motion-static-hover-surface";
const MOTION_FEED_SELECTION_MARKER_CLASS_NAME = "motion-feed-selection-marker";
export const MOTION_RESIZE_SURFACE_CLASS_NAME = "motion-resize-surface";
const MOTION_PRESSABLE_SURFACE_CLASS_NAME = "motion-pressable-surface";
export const MOTION_POPUP_SURFACE_CLASS_NAME = "motion-popup-surface";
export const MOTION_POPUP_OVERLAY_CLASS_NAME = "motion-popup-overlay";
export const MOTION_POPUP_DIALOG_CLASS_NAME = "motion-popup-dialog";
export const MOTION_BROWSER_OVERLAY_CLASS_NAME = "motion-browser-overlay-panel";
export const MOTION_BROWSER_THEME_WIPE_OVERLAY_CLASS_NAME = "motion-browser-theme-wipe-overlay";
export const MOTION_SETTINGS_MODAL_CLASS_NAME = "motion-settings-modal";
export const MOTION_STATE_TOGGLE_CLASS_NAME = "motion-state-toggle";
export const MOTION_ARTICLE_SELECTION_MARKER_CLASS_NAME = "motion-article-selection-marker";
export const MOTION_ARTICLE_STATE_SLOT_CLASS_NAME = "motion-article-state-slot";
export const MOTION_DIGIT_GROUP_CLASS_NAME = "t-digit-group";
export const MOTION_DIGIT_CLASS_NAME = "t-digit";
export const MOTION_DIGIT_ANIMATING_CLASS_NAME = "is-animating";
export const MOTION_ICON_SWAP_CLASS_NAME = "motion-icon-swap";
export const MOTION_ICON_SWAP_ICON_CLASS_NAME = "motion-icon-swap-icon";
const MOTION_FILTER_TOGGLE_CLASS_NAME = "motion-filter-toggle";
const MOTION_LIST_ITEM_ENTER_CLASS_NAME = "motion-list-item-enter";
const MOTION_LOADING_DOT_CLASS_NAME = "motion-loading-dot";
export const MOTION_HOLD_CONFIRM_CLASS_NAME = "motion-hold-confirm";
export const MOTION_HOLD_CONFIRM_FILL_CLASS_NAME = "motion-hold-confirm-fill";
export const MOTION_HOLD_CONFIRM_DURATION_MS = 2000;
export const MOTION_CLASS_NAMES = [
  MOTION_INTERACTIVE_SURFACE_CLASS_NAME,
  MOTION_BUTTON_SURFACE_CLASS_NAME,
  MOTION_DISCLOSURE_PANEL_CLASS_NAME,
  MOTION_DISCLOSURE_BODY_CLASS_NAME,
  MOTION_DISCLOSURE_TRIGGER_CLASS_NAME,
  MOTION_DISCLOSURE_ICON_CLASS_NAME,
  MOTION_CONTENT_SWAP_CLASS_NAME,
  MOTION_ARTICLE_SLIDE_CLASS_NAME,
  MOTION_CONTEXTUAL_SURFACE_CLASS_NAME,
  MOTION_STATIC_HOVER_SURFACE_CLASS_NAME,
  MOTION_FEED_SELECTION_MARKER_CLASS_NAME,
  MOTION_RESIZE_SURFACE_CLASS_NAME,
  MOTION_PRESSABLE_SURFACE_CLASS_NAME,
  MOTION_POPUP_SURFACE_CLASS_NAME,
  MOTION_POPUP_OVERLAY_CLASS_NAME,
  MOTION_POPUP_DIALOG_CLASS_NAME,
  MOTION_BROWSER_OVERLAY_CLASS_NAME,
  MOTION_BROWSER_THEME_WIPE_OVERLAY_CLASS_NAME,
  MOTION_SETTINGS_MODAL_CLASS_NAME,
  MOTION_STATE_TOGGLE_CLASS_NAME,
  MOTION_ARTICLE_SELECTION_MARKER_CLASS_NAME,
  MOTION_ARTICLE_STATE_SLOT_CLASS_NAME,
  MOTION_DIGIT_GROUP_CLASS_NAME,
  MOTION_DIGIT_CLASS_NAME,
  MOTION_DIGIT_ANIMATING_CLASS_NAME,
  MOTION_ICON_SWAP_CLASS_NAME,
  MOTION_ICON_SWAP_ICON_CLASS_NAME,
  MOTION_FILTER_TOGGLE_CLASS_NAME,
  MOTION_LIST_ITEM_ENTER_CLASS_NAME,
  MOTION_LOADING_DOT_CLASS_NAME,
  MOTION_HOLD_CONFIRM_CLASS_NAME,
  MOTION_HOLD_CONFIRM_FILL_CLASS_NAME,
] as const;
export type MotionClassName = (typeof MOTION_CLASS_NAMES)[number];

const MOTION_VERTICAL_WIPE_KEYFRAMES_NAME = "vertical-wipe";
const MOTION_CONTENT_SWAP_ENTER_KEYFRAMES_NAME = "motion-content-swap-enter";
const MOTION_ARTICLE_SLIDE_NEXT_KEYFRAMES_NAME = "motion-article-slide-next";
const MOTION_ARTICLE_SLIDE_PREV_KEYFRAMES_NAME = "motion-article-slide-prev";
const MOTION_SETTINGS_MODAL_ENTER_KEYFRAMES_NAME = "motion-settings-modal-enter";
const MOTION_STATE_TOGGLE_POP_KEYFRAMES_NAME = "motion-state-toggle-pop";
const MOTION_STAR_TOGGLE_POP_KEYFRAMES_NAME = "motion-star-toggle-pop";
const MOTION_ARTICLE_SELECTION_MARKER_KEYFRAMES_NAME = "motion-article-selection-marker";
const MOTION_DIGIT_POP_IN_KEYFRAMES_NAME = "t-digit-pop-in";
const MOTION_LOADING_PULSE_KEYFRAMES_NAME = "motion-loading-pulse";
const MOTION_LIST_ITEM_ENTER_KEYFRAMES_NAME = "motion-list-item-enter";
export const MOTION_KEYFRAMES_NAMES = [
  MOTION_VERTICAL_WIPE_KEYFRAMES_NAME,
  MOTION_CONTENT_SWAP_ENTER_KEYFRAMES_NAME,
  MOTION_ARTICLE_SLIDE_NEXT_KEYFRAMES_NAME,
  MOTION_ARTICLE_SLIDE_PREV_KEYFRAMES_NAME,
  MOTION_SETTINGS_MODAL_ENTER_KEYFRAMES_NAME,
  MOTION_STATE_TOGGLE_POP_KEYFRAMES_NAME,
  MOTION_STAR_TOGGLE_POP_KEYFRAMES_NAME,
  MOTION_ARTICLE_SELECTION_MARKER_KEYFRAMES_NAME,
  MOTION_DIGIT_POP_IN_KEYFRAMES_NAME,
  MOTION_LOADING_PULSE_KEYFRAMES_NAME,
  MOTION_LIST_ITEM_ENTER_KEYFRAMES_NAME,
] as const;
export type MotionKeyframesName = (typeof MOTION_KEYFRAMES_NAMES)[number];

export const MOTION_DATA_PHASE_ATTRIBUTE = "data-motion-phase";
export const MOTION_DATA_DIRECTION_ATTRIBUTE = "data-motion-direction";
const MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE = "data-article-slide-content";
export const MOTION_DATA_STATE_ATTRIBUTE = "data-state";
export const MOTION_DATA_ICON_ATTRIBUTE = "data-icon";
const MOTION_DATA_SIDE_ATTRIBUTE = "data-side";
export const MOTION_DATA_STAGGER_ATTRIBUTE = "data-stagger";
const MOTION_DATA_OPEN_ATTRIBUTE = "data-open";
const MOTION_DATA_CLOSED_ATTRIBUTE = "data-closed";
const MOTION_DATA_STARTING_STYLE_ATTRIBUTE = "data-starting-style";
const MOTION_DATA_ENDING_STYLE_ATTRIBUTE = "data-ending-style";
const MOTION_DATA_FILTER_TOGGLE_CONTENT_ATTRIBUTE = "data-filter-toggle-content";
const MOTION_DATA_PRESSED_ATTRIBUTE = "data-pressed";
const MOTION_DATA_STATE_TOGGLE_ICON_ATTRIBUTE = "data-state-toggle-icon";
const MOTION_DATA_STATE_TOGGLE_ICON_TONE_ATTRIBUTE = "data-state-toggle-icon-tone";
const MOTION_DATA_ARTICLE_STATE_SLOT_ATTRIBUTE = "data-article-state-slot";
export const MOTION_DATA_HOLD_ATTRIBUTE = "data-motion-hold";
export const MOTION_DATA_ATTRIBUTES = [
  MOTION_DATA_PHASE_ATTRIBUTE,
  MOTION_DATA_DIRECTION_ATTRIBUTE,
  MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE,
  MOTION_DATA_ARTICLE_STATE_SLOT_ATTRIBUTE,
  MOTION_DATA_STATE_ATTRIBUTE,
  MOTION_DATA_ICON_ATTRIBUTE,
  MOTION_DATA_SIDE_ATTRIBUTE,
  MOTION_DATA_STAGGER_ATTRIBUTE,
  MOTION_DATA_OPEN_ATTRIBUTE,
  MOTION_DATA_CLOSED_ATTRIBUTE,
  MOTION_DATA_STARTING_STYLE_ATTRIBUTE,
  MOTION_DATA_ENDING_STYLE_ATTRIBUTE,
  MOTION_DATA_FILTER_TOGGLE_CONTENT_ATTRIBUTE,
  MOTION_DATA_PRESSED_ATTRIBUTE,
  MOTION_DATA_STATE_TOGGLE_ICON_ATTRIBUTE,
  MOTION_DATA_STATE_TOGGLE_ICON_TONE_ATTRIBUTE,
  MOTION_DATA_HOLD_ATTRIBUTE,
] as const;
export type MotionDataAttribute = (typeof MOTION_DATA_ATTRIBUTES)[number];

const MOTION_POPUP_SIDE_TOP = "top";
const MOTION_POPUP_SIDE_RIGHT = "right";
const MOTION_POPUP_SIDE_BOTTOM = "bottom";
const MOTION_POPUP_SIDE_LEFT = "left";
const MOTION_POPUP_SIDES = [
  MOTION_POPUP_SIDE_TOP,
  MOTION_POPUP_SIDE_RIGHT,
  MOTION_POPUP_SIDE_BOTTOM,
  MOTION_POPUP_SIDE_LEFT,
] as const;

export const MOTION_PHASE_STEADY = "steady";
export const MOTION_PHASE_ENTERING = "entering";
export type MotionPhase = typeof MOTION_PHASE_STEADY | typeof MOTION_PHASE_ENTERING;

export const MOTION_DIRECTION_NEXT = "next";
export const MOTION_DIRECTION_PREV = "prev";
export const MOTION_DIRECTION_NEUTRAL = "neutral";
export type MotionDirection =
  | typeof MOTION_DIRECTION_NEXT
  | typeof MOTION_DIRECTION_PREV
  | typeof MOTION_DIRECTION_NEUTRAL;

export const MOTION_STATE_OPEN = "open";
export const MOTION_STATE_CLOSED = "closed";

export const BROWSER_OVERLAY_CLOSE_DELAY_MS = 350;

export const MOTION_ICON_SWAP_STATE_A = "a";
export const MOTION_ICON_SWAP_STATE_B = "b";
export type MotionIconSwapState = typeof MOTION_ICON_SWAP_STATE_A | typeof MOTION_ICON_SWAP_STATE_B;

export const MOTION_ICON_SWAP_ICON_A = "a";
export const MOTION_ICON_SWAP_ICON_B = "b";

export const MOTION_DIGIT_STAGGER_ONE = "1";
export const MOTION_DIGIT_STAGGER_TWO = "2";
export type MotionDigitStagger = typeof MOTION_DIGIT_STAGGER_ONE | typeof MOTION_DIGIT_STAGGER_TWO;

export const MOTION_TRANSITION_TOKEN_DECLARATIONS = [
  "--motion-duration-disclosure: 200ms;",
  "--motion-duration-popup: 160ms;",
  "--motion-duration-resize: 260ms;",
  "--motion-duration-theme: 180ms;",
  "--motion-duration-contextual: 180ms;",
  "--motion-duration-content-swap: 180ms;",
  "--motion-duration-hold-confirm: 2000ms;",
  "--motion-duration-hold-confirm-release: 200ms;",
  "--motion-duration-popup-enter: 200ms;",
  "--motion-duration-popup-exit: 120ms;",
  "--motion-ease-standard: cubic-bezier(0.22, 1, 0.36, 1);",
  "--motion-ease-emphasized: cubic-bezier(0.2, 0.8, 0.2, 1);",
] as const;
export type MotionTransitionTokenDeclaration = (typeof MOTION_TRANSITION_TOKEN_DECLARATIONS)[number];

export const MOTION_GLOBAL_CSS_CONTRACT_SELECTORS = [
  `.${MOTION_BROWSER_THEME_WIPE_OVERLAY_CLASS_NAME}`,
  `.${MOTION_DISCLOSURE_PANEL_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_STATE_OPEN}"]`,
  `.${MOTION_DISCLOSURE_PANEL_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_STATE_CLOSED}"]`,
  `.${MOTION_DISCLOSURE_PANEL_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_STATE_OPEN}"] > .${MOTION_DISCLOSURE_BODY_CLASS_NAME}`,
  `.${MOTION_DISCLOSURE_PANEL_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_STATE_CLOSED}"] > .${MOTION_DISCLOSURE_BODY_CLASS_NAME}`,
  `.${MOTION_CONTENT_SWAP_CLASS_NAME}[${MOTION_DATA_PHASE_ATTRIBUTE}="${MOTION_PHASE_ENTERING}"]`,
  `.${MOTION_ARTICLE_SLIDE_CLASS_NAME}[${MOTION_DATA_DIRECTION_ATTRIBUTE}="${MOTION_DIRECTION_NEXT}"]`,
  `.${MOTION_ARTICLE_SLIDE_CLASS_NAME}[${MOTION_DATA_DIRECTION_ATTRIBUTE}="${MOTION_DIRECTION_PREV}"]`,
  `[${MOTION_DATA_ARTICLE_SLIDE_CONTENT_ATTRIBUTE}="true"]`,
  `.${MOTION_DIGIT_GROUP_CLASS_NAME}.${MOTION_DIGIT_ANIMATING_CLASS_NAME} .${MOTION_DIGIT_CLASS_NAME}`,
  `.${MOTION_DIGIT_GROUP_CLASS_NAME}.${MOTION_DIGIT_ANIMATING_CLASS_NAME} .${MOTION_DIGIT_CLASS_NAME}[${MOTION_DATA_STAGGER_ATTRIBUTE}="${MOTION_DIGIT_STAGGER_ONE}"]`,
  `.${MOTION_DIGIT_GROUP_CLASS_NAME}.${MOTION_DIGIT_ANIMATING_CLASS_NAME} .${MOTION_DIGIT_CLASS_NAME}[${MOTION_DATA_STAGGER_ATTRIBUTE}="${MOTION_DIGIT_STAGGER_TWO}"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_A}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_A}"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_B}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_B}"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_A}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_B}"]`,
  `.${MOTION_ICON_SWAP_CLASS_NAME}[${MOTION_DATA_STATE_ATTRIBUTE}="${MOTION_ICON_SWAP_STATE_B}"] > .${MOTION_ICON_SWAP_ICON_CLASS_NAME}[${MOTION_DATA_ICON_ATTRIBUTE}="${MOTION_ICON_SWAP_ICON_A}"]`,
  ...MOTION_POPUP_SIDES.map((side) => `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_SIDE_ATTRIBUTE}="${side}"]`),
  `.${MOTION_POPUP_OVERLAY_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}]`,
  `.${MOTION_POPUP_OVERLAY_CLASS_NAME}[${MOTION_DATA_CLOSED_ATTRIBUTE}]`,
  `.${MOTION_POPUP_DIALOG_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}]`,
  `.${MOTION_POPUP_DIALOG_CLASS_NAME}[${MOTION_DATA_CLOSED_ATTRIBUTE}]`,
  `.${MOTION_POPUP_DIALOG_CLASS_NAME}[${MOTION_DATA_STARTING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_POPUP_DIALOG_CLASS_NAME}[${MOTION_DATA_ENDING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_CLOSED_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_STARTING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_POPUP_SURFACE_CLASS_NAME}[${MOTION_DATA_ENDING_STYLE_ATTRIBUTE}]`,
  `.${MOTION_BROWSER_OVERLAY_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}="false"] *`,
  `.${MOTION_BROWSER_OVERLAY_CLASS_NAME}[${MOTION_DATA_OPEN_ATTRIBUTE}="true"]`,
  `.${MOTION_HOLD_CONFIRM_FILL_CLASS_NAME}`,
  `.${MOTION_HOLD_CONFIRM_CLASS_NAME}[${MOTION_DATA_HOLD_ATTRIBUTE}="true"] > .${MOTION_HOLD_CONFIRM_FILL_CLASS_NAME}`,
] as const;
export type MotionGlobalCssContractSelector = (typeof MOTION_GLOBAL_CSS_CONTRACT_SELECTORS)[number];
