export const SIDEBAR_PANE_WIDTH_PX = 280;
export const ARTICLE_LIST_PANE_WIDTH_PX = 380;

export const MOBILE_LAYOUT_BREAKPOINT_PX = 640;
export const COMPACT_LAYOUT_BREAKPOINT_PX = 1100;

export const FEED_CLEANUP_SPLIT_LAYOUT_WIDTH_PX = 900;
export const FEED_CLEANUP_WIDE_LAYOUT_WIDTH_PX = 1180;
