export const APP_HIDDEN_DURATION_SYNC_THRESHOLD_MS = 30_000;
export const STARTUP_SYNC_THROTTLE_MS = 90_000;
export const TOAST_AUTO_DISMISS_TIMEOUT_MS = 4_000;
export const TOAST_EXIT_DURATION_MS = 160;
